- name: Create deploy dir
  file:
    path: "{{ deploy_dir }}{{ deploy_app_name }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
    enabled: true

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: true
